Update build requirements, at least Gwenhyfar 4.0.3 is required
Otherwise the build will fail with error: undefined reference to `GWEN_Gui_SetCharSet'


git-svn-id: https://devel.aqbanking.de/svn/aqbanking/trunk@2136 5c42a225-8b10-0410-9873-89b7810ad06e