fixed a nasty bug (why doesn't GCC tell me *what* symbol is missing instead of 'undefined reference to vtable'... grrrrr.
git-svn-id: https://devel.aqbanking.de/svn/aqbanking/trunk@34 5c42a225-8b10-0410-9873-89b7810ad06e